export type RootStackParamList = {
  Splash: undefined;
  Home: undefined;
  Login: undefined;
  Register: undefined;
  CompletePlayerProfile: undefined;
  UserPanel: undefined;
  PlayerProfile: undefined;
  PlayerList: undefined;
  PlayerDetail: { playerId: number };
  EditPlayerProfile: undefined;
  MyReviews: undefined;
  TeamList: undefined;
  TeamDetail: { teamId: number };
  CreateTeam: undefined;
  MyTeam: undefined;
  ChangeCaptain: undefined;
  SelectTeam1: undefined;
  SelectTeam2: undefined;
  TeamCompare: undefined;
  TopTeams: undefined;
  TopPlayers: undefined;
  MatchList: undefined;
  MatchDetail: { matchId: number };
  CreateMatch: undefined;
  MyMatches: undefined;
  MatchCalendar: undefined;
  MatchReviews: { matchId: number };
  CreateReview: { matchId: number };
  SendOffer: { receiverId: number };
  MyOffers: undefined;
  CaptainOffer: undefined;
  MarkAttendance: undefined;
  MatchStats: undefined;
  Turnuva: undefined;
};
